### ISSUE TITLE
Maliamungu Richard.md

### ISSUE THREAD

**Issue by gibertgibs** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#19]

**Comment by maliarich** [comment]
**_My names are Maliamungu Richard, a south Sudanese living in Rhino camp which is due to the civil war that
erupted in 2016 back in the country, hence I  ended in high school due to tuition as such DIY become the solution, online studies
,reading tech related books and engaging and encouraging local innovators and do basic repair liking fixing electronic devices , building solar charger, or LED lights. 

I love tech related things since child hood. My journey into tech innovations started in 2018 when I  participated in an Open Tech  workshop organized  by r0g agency, hosted by Cten Uganda in Eden, Rhino camp refugee settlement which I then facilitated an open tech event (IoT day) in Adjumany, Uganda Organized by Youth Empowerment Foundation (#YEF) .This becomes a journey into becoming tech repairer with Cten Uganda and in the  #ASKnet 2020 project, I worked as an Adjuct Trainer for r0g agency._**

**Comment by bmen** [comment]
Content taken over to: https://asknet-open-training.github.io/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/Maliamungu-Richard/
