### ISSUE TITLE
Richard Gama.md

### ISSUE THREAD

**Issue by gibertgibs** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#34]

**Comment by PyGamma** [comment]
![17-BSS-BU-R-0005](https://user-images.githubusercontent.com/38918594/114106841-574db380-98d8-11eb-923d-740be750532d.jpg)
I am called GAMA RICHARD WILLIAM, a South Sudan based in Uganda due to the civil unrest in South Sudan. I have been in Uganda for several years. My experience in Uganda and in Refugees camps in Particular has instill in me a desire to strive for transformed society where quality of life is sustainably improved. I am a trained software engineer from Bugema University who loves building web application delivered through cloud SaaS model of Cloud computing 
I am passionate about empowering local community about Digital Literacy so that they can harness the power of technology to achieve their societal dreams. My engagement with r0g agency has being through The Youth Empowerment Foundation where I volunteer as IT support staff and this has enlightened me about the noble course of the open source world. I am on trajectory to becoming Civic Educator and Peace Advocate

**Comment by bmen** [comment]
last contents taken over: https://asknet-open-training.github.io/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/Richard-Gama/
